blank_issues_enabled: false
contact_links:
   - name: Support
     url: https://github.com/michalowskil/lovelace-touchpad-card/discussions
     about: If you don't want to report a bug but just want to ask a question, click here.